/*
 * Licensed to ElasticSearch and Shay Banon under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership. ElasticSearch licenses this
 * file to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

package org.elasticsearch.search.aggregations.bucket.histogram;

import org.elasticsearch.common.Rounding;
import org.elasticsearch.common.trove.ExtTLongObjectHashMap;
import org.elasticsearch.script.SearchScript;
import org.elasticsearch.search.aggregations.Aggregator;
import org.elasticsearch.search.aggregations.InternalAggregation;
import org.elasticsearch.search.aggregations.bucket.BucketAggregator;

import java.util.ArrayList;
import java.util.Collections;
import java.util.List;

/**
 * A histogram aggregator which aggregates values generated by a script.
 */
public class ScriptHistogramAggregator extends BucketAggregator implements ScriptHistogramCollector.Listener {

    private final SearchScript script;
    private final Rounding rounding;
    private final InternalOrder order;
    private final boolean keyed;

    ExtTLongObjectHashMap<ScriptHistogramCollector.BucketCollector> collectors;

    public ScriptHistogramAggregator(String name, List<Aggregator.Factory> factories,
                                     SearchScript script, long interval, InternalOrder order, boolean keyed, Aggregator parent) {
        super(name, factories, parent);
        this.script = script;
        this.rounding = new Rounding.Interval(interval);
        this.order = order;
        this.keyed = keyed;
    }

    @Override
    public ScriptHistogramCollector collector() {
        return new ScriptHistogramCollector(this, script, rounding, this);
    }

    @Override
    public InternalAggregation buildAggregation() {
        List<Histogram.Bucket> buckets = new ArrayList<Histogram.Bucket>(collectors.size());
        for (Object collector : collectors.internalValues()) {
            if (collector == null) {
                continue;
            }
            ScriptHistogramCollector.BucketCollector bucketCollector = (ScriptHistogramCollector.BucketCollector) collector;
            List<InternalAggregation> aggregations = new ArrayList<InternalAggregation>(bucketCollector.aggregators.size());
            for (Aggregator aggregator : bucketCollector.aggregators) {
                aggregations.add(aggregator.buildAggregation());
            }
            buckets.add(new InternalHistogram.Bucket(bucketCollector.key, bucketCollector.docCount, aggregations));
        }
        Collections.sort(buckets, order.comparator());
        return new InternalHistogram(name, buckets, order, keyed);
    }

    @Override
    public void onFinish(ExtTLongObjectHashMap<ScriptHistogramCollector.BucketCollector> collectors) {
        this.collectors = collectors;
    }

    public static class Factory extends BucketAggregator.Factory<ScriptHistogramAggregator, Factory> {

        private final SearchScript script;
        private final long interval;
        private final InternalOrder order;
        private final boolean keyed;

        public Factory(String name, SearchScript script, long interval, InternalOrder order, boolean keyed) {
            super(name);
            this.script = script;
            this.interval = interval;
            this.order = order;
            this.keyed = keyed;
        }

        @Override
        public ScriptHistogramAggregator create(Aggregator parent) {
            return new ScriptHistogramAggregator(name, factories, script, interval, order, keyed, parent);
        }
    }

}
